# Generated by Django 6.0.1 on 2026-03-21 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email de connexion')),
                ('nom_officine', models.CharField(max_length=255, verbose_name="Nom de l'Officine")),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET')),
                ('address1', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de TVA')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sms_credits', models.PositiveIntegerField(default=0, verbose_name='Crédits SMS')),
                ('pharmacy_type', models.CharField(blank=True, choices=[('urbaine', 'Urbaine'), ('rurale', 'Rurale'), ('centre-bourg', 'Centre Bourg'), ('centre-commercial', 'Centre Commercial')], default='urbaine', max_length=20, verbose_name='Type de pharmacie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/', verbose_name='Logo')),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email en attente')),
                ('email_verification_token', models.UUIDField(blank=True, null=True, verbose_name='Token de vérification email')),
                ('email_verification_expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Abonnement Premium')),
                ('is_active', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding complété')),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template SMS',
                'verbose_name_plural': 'Templates SMS',
                'unique_together': {('pharmacy', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_hash', models.CharField(max_length=64)),
                ('recipient_civilite', models.CharField(blank=True, max_length=3)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=10)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.smstemplate')),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
                'ordering': ['-sent_at'],
            },
        ),
    ]
