# Generated by Django 6.0.1 on 2026-03-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='ovh_message_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', "En cours d'envoi"), ('SUCCESS', 'Envoyé'), ('DELIVERED', 'Livré'), ('FAILED', 'Échec')], default='PENDING', max_length=10),
        ),
    ]
