# Generated by Django 5.2.8 on 2025-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='adresse',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 1'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_type',
            field=models.CharField(blank=True, choices=[('urbaine', 'Urbaine'), ('rurale', 'Rurale'), ('centre-bourg', 'Centre Bourg'), ('centre-commercial', 'Centre Commercial')], default='urbaine', max_length=20, verbose_name='Type de pharmacie'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de TVA'),
        ),
    ]
