# Generated by Django 6.0.1 on 2026-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pharmacy_adresse_pharmacy_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding complété'),
        ),
    ]
