# Generated by Django 6.0.1 on 2026-03-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pharmacy_sms_credits_check'),
        ('team', '0008_add_color_hex_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent', to='team.collaborator'),
        ),
    ]
