# Generated by Django 6.0.1 on 2026-03-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_smslog_sent_by_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
    ]
