# Generated by Django 6.0.1 on 2026-03-17 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pharmacy_sms_credits_smstemplate_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_variables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variable personnalisée',
                'verbose_name_plural': 'Variables personnalisées',
                'ordering': ['name'],
                'unique_together': {('pharmacy', 'name')},
            },
        ),
    ]
