# Generated by Django 6.0.1 on 2026-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_ovh_message_id_provider_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='sms_credits',
            field=models.PositiveIntegerField(default=20, verbose_name='Crédits SMS'),
        ),
    ]
