# Generated by Django 6.0.1 on 2026-04-11 18:50

from django.db import migrations


def credit_existing_accounts(apps, schema_editor):
    Pharmacy = apps.get_model('core', 'Pharmacy')
    Pharmacy.objects.filter(sms_credits=0).update(sms_credits=20)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sms_credits_default_20'),
    ]

    operations = [
        migrations.RunPython(credit_existing_accounts, migrations.RunPython.noop),
    ]
