# Generated by Django 6.0.1 on 2026-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compte anonymisé le'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suppression demandée le'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suppression programmée pour'),
        ),
    ]
