# Generated by Django 6.0.1 on 2026-07-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pharmacy_anonymized_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='phone',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone_fixe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone portable'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='region',
            field=models.CharField(blank=True, choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Île-de-France', 'Île-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur"), ('Guadeloupe', 'Guadeloupe'), ('Martinique', 'Martinique'), ('Guyane', 'Guyane'), ('La Réunion', 'La Réunion'), ('Mayotte', 'Mayotte')], max_length=100, verbose_name='Région'),
        ),
    ]
