# Generated by Django 6.0.1 on 2026-07-23 04:58

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pharmacy_phone_pharmacy_phone_fixe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=apps.core.models.logo_storage, upload_to='pharmacy_logos/', verbose_name='Logo'),
        ),
    ]
