# Generated by Django 6.0.1 on 2026-03-21 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Autre', 'Autre')], default='M.', max_length=10, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('Titulaire', 'Titulaire'), ('Adjoint', 'Adjoint'), ('Préparateur', 'Préparateur'), ('Étudiant', 'Étudiant'), ('Apprenti', 'Apprenti')], default='Préparateur', max_length=20, verbose_name='Rôle')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='Hash du PIN')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Couleur')),
                ('can_manage_account', models.BooleanField(default=False, verbose_name='Gérer le compte')),
                ('can_manage_team', models.BooleanField(default=False, verbose_name="Gérer l'équipe")),
                ('can_manage_planning', models.BooleanField(default=False, verbose_name='Gérer le planning')),
                ('can_manage_quality', models.BooleanField(default=False, verbose_name='Gérer la qualité')),
                ('can_manage_procedures', models.BooleanField(default=False, verbose_name='Gérer les procédures')),
                ('can_publish_procedures', models.BooleanField(default=False, verbose_name='Publier les procédures')),
                ('can_close_nonconformities', models.BooleanField(default=False, verbose_name='Clôturer les non-conformités')),
                ('can_assign_task', models.BooleanField(default=False, verbose_name='Assigner des tâches')),
                ('contract_type', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('apprenti', 'Apprentissage'), ('interim', 'Intérim')], default='cdi', max_length=10)),
                ('weekly_hours', models.DecimalField(decimal_places=1, default=35.0, max_digits=4, verbose_name='Heures hebdomadaires contractuelles')),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacie de rattachement')),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'ordering': ['display_order', 'id'],
                'unique_together': {('pharmacy', 'first_name', 'last_name')},
            },
        ),
    ]
