# Generated by Django 5.2.8 on 2025-11-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('TITULAIRE', 'Titulaire'), ('ADJOINT', 'Adjoint'), ('PREPARATEUR', 'Préparateur'), ('RAYONNISTE', 'Rayonniste'), ('ETUDIANT', 'Étudiant / Apprenti'), ('AUTRE', 'Autre')], default='ADJOINT', max_length=20, verbose_name='Rôle')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='Hash du PIN')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacie de rattachement')),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'unique_together': {('pharmacy', 'first_name', 'last_name')},
            },
        ),
    ]
