# Generated by Django 5.2.8 on 2025-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='civility',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme', 'Mme'), ('Autre', 'Autre')], default='M.', max_length=10, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(choices=[('Titulaire', 'Titulaire'), ('Adjoint', 'Adjoint'), ('Préparateur', 'Préparateur'), ('Étudiant', 'Étudiant'), ('Apprenti', 'Apprenti')], default='Préparateur', max_length=20, verbose_name='Rôle'),
        ),
    ]
