# Generated by Django 6.0.1 on 2026-03-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='contract_type',
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('APPRENTISSAGE', 'Apprentissage'), ('INTERIM', 'Intérim'), ('TNS', 'TNS')], max_length=20)),
                ('weekly_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='team.collaborator')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
