# Generated by Django 6.0.1 on 2026-03-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_collaborator_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel'),
        ),
    ]
