# Generated by Django 6.0.1 on 2026-03-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_add_is_tns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthistory',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='team.collaborator'),
        ),
    ]
