# Generated by Django 6.0.1 on 2026-03-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_collaborator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('apprenti', 'Apprentissage'), ('interim', 'Intérim')], default='cdi', max_length=10),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=1, default=35.0, max_digits=4, verbose_name='Heures hebdomadaires contractuelles'),
        ),
    ]
