# Generated by Django 6.0.1 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_collaborator_contract_type_collaborator_weekly_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Collaborateur', 'verbose_name_plural': 'Collaborateurs'},
        ),
        migrations.AddField(
            model_name='collaborator',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
