# Generated by Django 6.0.1 on 2026-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_loginlog_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='pin_fail_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Échecs PIN consécutifs'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'à"),
        ),
    ]
