# Generated by Django 6.0.1 on 2026-03-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_add_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
    ]
