# Generated by Django 6.0.1 on 2026-03-23 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_add_pin_lockout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être au format hexadécimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur'),
        ),
    ]
