# Generated by Django 6.0.1 on 2026-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_collaborator_quality_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='can_assign_task',
            field=models.BooleanField(default=False, verbose_name='Assigner des tâches'),
        ),
    ]
