# Generated by Django 6.0.1 on 2026-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inactivity_ad_image', models.ImageField(blank=True, null=True, upload_to='ads/inactivity/', verbose_name='Image Pub Inactivité')),
                ('inactivity_ad_link', models.URLField(blank=True, null=True, verbose_name='Lien de la pub')),
                ('inactivity_ad_active', models.BooleanField(default=False, verbose_name='Pub active')),
                ('inactivity_ad_priority', models.PositiveIntegerField(default=1, verbose_name='Priorité (1-10)')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
            },
        ),
    ]
