# Generated by Django 5.2.8 on 2025-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='inactivity_ad_active',
            field=models.BooleanField(default=False, verbose_name='Pub active'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inactivity_ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/inactivity/', verbose_name='Image Pub Inactivité'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inactivity_ad_link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de la pub'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inactivity_ad_priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Priorité (1-10)'),
        ),
    ]
