# Generated by Django 6.0.1 on 2026-03-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
