# Generated by Django 6.0.1 on 2026-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_delete_attachment'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to='team.collaborator', verbose_name='Masquée par'),
        ),
    ]
