# Generated by Django 6.0.1 on 2026-04-12 00:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_hidden_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='subject',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Sujet'),
        ),
    ]
