# Generated by Django 6.0.1 on 2026-06-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('subscription', 'Abonnement'), ('sms_pack', 'Pack SMS')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['pharmacy', 'issued_at'], name='bill_inv_phcy_date_idx'), models.Index(fields=['invoice_type'], name='bill_inv_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('invoice_type__in', ['subscription', 'sms_pack'])), name='billing_invoice_type_valid'), models.CheckConstraint(condition=models.Q(('amount_ht__gte', 0)), name='billing_invoice_amount_ht_positive')],
            },
        ),
        migrations.CreateModel(
            name='SmsCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Achat de pack'), ('send', 'Envoi SMS'), ('refund', 'Remboursement')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction SMS',
                'verbose_name_plural': 'Transactions SMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pharmacy', 'created_at'], name='bill_sms_tx_phcy_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plan', models.CharField(choices=[('small', 'Small (< 10 collaborateurs)'), ('large', 'Large (≥ 10 collaborateurs)')], default='small', max_length=10)),
                ('status', models.CharField(choices=[('trialing', "Période d'essai"), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('suspended', 'Suspendu'), ('canceled', 'Résilié')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'indexes': [models.Index(fields=['status'], name='bill_sub_status_idx'), models.Index(fields=['trial_ends_at'], name='bill_sub_trial_idx'), models.Index(fields=['current_period_end'], name='bill_sub_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('plan__in', ['small', 'large'])), name='billing_subscription_plan_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due', 'suspended', 'canceled'])), name='billing_subscription_status_valid')],
            },
        ),
    ]
