# Generated by Django 6.0.1 on 2026-06-24 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('months_free', models.PositiveSmallIntegerField(help_text="Nombre de mois offerts après le mois d'essai.")),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un usage illimité globalement.', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Laisser vide si pas de date d'expiration.", null=True)),
                ('note', models.CharField(blank=True, help_text='Usage interne uniquement (ex: Offre groupement Giphar).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='billing_promocode_code_idx'), models.Index(fields=['is_active'], name='billing_promocode_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('months_free__gte', 1)), name='billing_promocode_months_free_min_1')],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.promocode')),
            ],
            options={
                'verbose_name': 'Utilisation code promo',
                'verbose_name_plural': 'Utilisations codes promo',
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['pharmacy'], name='bill_promo_redempt_phcy_idx')],
                'constraints': [models.UniqueConstraint(fields=('promo_code', 'pharmacy'), name='billing_promoredemption_unique_per_pharmacy')],
            },
        ),
    ]
