# Generated by Django 6.0.1 on 2026-06-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
