# Generated by Django 6.0.1 on 2026-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscredittransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Achat de pack'), ('send', 'Envoi SMS'), ('refund', 'Remboursement'), ('closure', 'Clôture du compte')], max_length=20),
        ),
    ]
