# Generated by Django 6.0.1 on 2026-06-27 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_smscredittransaction_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smscredittransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='smscredittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id__isnull', False)), fields=('stripe_payment_intent_id',), name='bill_sms_tx_pi_unique'),
        ),
    ]
