# Generated by Django 6.0.1 on 2026-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_smscredittransaction_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, help_text='Entrée en impayé — origine du délai de grâce de 7 jours.', null=True),
        ),
    ]
