# Generated by Django 6.0.1 on 2026-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
