# Generated by Django 6.0.1 on 2026-04-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminuser_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_OK', 'Connexion réussie'), ('LOGIN_FAIL', 'Connexion échouée'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement de mot de passe'), ('TOTP_SETUP', 'Configuration TOTP'), ('RESOURCE_CREATE', 'Création ressource'), ('RESOURCE_UPDATE', 'Modification ressource'), ('RESOURCE_DELETE', 'Suppression ressource'), ('ITEM_CREATE', 'Ajout item'), ('ITEM_DELETE', 'Suppression item'), ('RECOMMEND_APPROVE', 'Approbation recommandation'), ('RECOMMEND_REJECT', 'Rejet recommandation')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='admin_panel.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
