# Generated by Django 6.0.1 on 2026-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_OK', 'Connexion réussie'), ('LOGIN_FAIL', 'Connexion échouée'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement de mot de passe'), ('TOTP_SETUP', 'Configuration TOTP'), ('RESOURCE_CREATE', 'Création ressource'), ('RESOURCE_UPDATE', 'Modification ressource'), ('RESOURCE_DELETE', 'Suppression ressource'), ('ITEM_CREATE', 'Ajout item'), ('ITEM_DELETE', 'Suppression item'), ('RECOMMEND_APPROVE', 'Approbation recommandation'), ('RECOMMEND_REJECT', 'Rejet recommandation'), ('SUBSCRIPTION_UPDATE', 'Modification abonnement'), ('PROMO_UPDATE', 'Modification code promo')], max_length=30),
        ),
    ]
