# Generated by Django 6.0.1 on 2026-03-21 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Mineure'), ('major', 'Majeure'), ('critical', 'Critique')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('closed', 'Clôturée')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ncs', to='team.collaborator')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ncs', to='team.collaborator')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ncs', to='team.collaborator')),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='team.collaborator')),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='quality.nonconformity')),
            ],
            options={
                'verbose_name': 'Action corrective',
                'verbose_name_plural': 'Actions correctives',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='quality/procedures/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_procedures', to='team.collaborator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedures', to='team.collaborator')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='quality.procedure')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to=settings.AUTH_USER_MODEL)),
                ('pilots', models.ManyToManyField(blank=True, related_name='piloted_procedures', to='team.collaborator')),
            ],
            options={
                'verbose_name': 'Procédure',
                'verbose_name_plural': 'Procédures',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='quality.procedure'),
        ),
        migrations.CreateModel(
            name='ProcedureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quality/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality.procedure')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='team.collaborator')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#2E7D32', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedure_categories', to='team.collaborator')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie de procédure',
                'verbose_name_plural': 'Catégories de procédure',
                'ordering': ['name'],
                'unique_together': {('name', 'pharmacy')},
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='procedures', to='quality.procedurecategory'),
        ),
        migrations.CreateModel(
            name='ProcedureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2E7D32', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedure_groups', to='team.collaborator')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tableau de procédures',
                'verbose_name_plural': 'Tableaux de procédures',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'pharmacy')},
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='quality.proceduregroup'),
        ),
        migrations.CreateModel(
            name='ProcedureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quality.procedure')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ProcedureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quality.procedure')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_notifications', to='team.collaborator')),
            ],
            options={
                'verbose_name': 'Notification procédure',
                'verbose_name_plural': 'Notifications procédures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('pharmacy', 'reference')},
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('change_summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé des modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_versions', to='team.collaborator', verbose_name='Auteur')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quality.procedure', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Version de procédure',
                'verbose_name_plural': 'Versions de procédure',
                'ordering': ['-version_number'],
                'unique_together': {('procedure', 'version_number')},
            },
        ),
    ]
