# Generated by Django 6.0.1 on 2026-03-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
