# Generated by Django 6.0.1 on 2026-03-18 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_procedure_is_group_alter_procedure_reference'),
        ('team', '0008_collaborator_quality_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2E7D32', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedure_groups', to='team.collaborator')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tableau de procédures',
                'verbose_name_plural': 'Tableaux de procédures',
                'ordering': ['name'],
                'unique_together': {('name', 'pharmacy')},
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='quality.proceduregroup'),
        ),
    ]
