# Generated by Django 6.0.1 on 2026-03-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_proceduregroup_procedure_group'),
        ('team', '0008_collaborator_quality_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='pilot',
        ),
        migrations.AddField(
            model_name='procedure',
            name='pilots',
            field=models.ManyToManyField(blank=True, related_name='piloted_procedures', to='team.collaborator'),
        ),
    ]
