# Generated by Django 6.0.1 on 2026-03-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_pg_indexes_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonconformities', to='quality.procedure'),
        ),
    ]
