# Generated by Django 6.0.1 on 2026-03-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_pilot_fk_to_m2m'),
        ('team', '0008_collaborator_quality_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('change_summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé des modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_versions', to='team.collaborator', verbose_name='Auteur')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quality.procedure', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Version de procédure',
                'verbose_name_plural': 'Versions de procédure',
                'ordering': ['-version_number'],
                'unique_together': {('procedure', 'version_number')},
            },
        ),
    ]
