# Generated by Django 6.0.1 on 2026-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_nc_procedure_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecategory',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedurecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proceduregroup',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceduregroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
