# Generated by Django 6.0.1 on 2026-03-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_procedurecategory_categories_m2m_attachment_fields'),
        ('team', '0008_collaborator_quality_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduregroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tableau de procédures', 'verbose_name_plural': 'Tableaux de procédures'},
        ),
        migrations.AddField(
            model_name='procedure',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_procedures', to='team.collaborator'),
        ),
        migrations.AddField(
            model_name='proceduregroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
