# Generated by Django 6.0.1 on 2026-03-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_procedure_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='quality.procedure'),
        ),
    ]
