# Generated by Django 6.0.1 on 2026-03-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_procedure_review_date'),
        ('team', '0008_collaborator_quality_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quality.procedure')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_notifications', to='team.collaborator')),
            ],
            options={
                'verbose_name': 'Notification procédure',
                'verbose_name_plural': 'Notifications procédures',
                'ordering': ['-created_at'],
            },
        ),
    ]
