# Generated by Django 6.0.1 on 2026-03-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
