# Generated by Django 5.2.8 on 2025-11-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la catégorie')),
                ('icon_slug', models.CharField(default='folder', max_length=50, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('owner_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacie propriétaire')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre'],
                'unique_together': {('owner_pharmacy', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ResourceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre de la carte')),
                ('description_officielle', models.TextField(blank=True, verbose_name='Description officielle')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cards/logos/')),
                ('type', models.CharField(choices=[('OFFICIAL', 'Officiel (Validé Admin)'), ('PARTNER', 'Partenaire (Géré par Labo)'), ('PRIVATE', 'Privé (Créé par Pharmacie)')], default='PRIVATE', max_length=20, verbose_name='Type de carte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='resources.category', verbose_name="Catégorie d'affichage par défaut")),
                ('owner_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('owner_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte de Ressource',
                'verbose_name_plural': 'Cartes de Ressources',
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WEB', 'Site Web'), ('PDF', 'Document PDF'), ('TEL', 'Numéro de téléphone'), ('MAIL', 'Adresse Email')], default='WEB', max_length=10, verbose_name="Type d'élément")),
                ('label', models.CharField(max_length=100, verbose_name='Libellé du lien')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='cards/files/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resourcecard')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élément de Ressource',
                'verbose_name_plural': 'Éléments de Ressources',
            },
        ),
        migrations.CreateModel(
            name='PharmacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('notes_perso', models.TextField(blank=True, verbose_name='Notes Privées')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_preferences', to='resources.category', verbose_name='Catégorie assignée par le pharmacien')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='resources.resourcecard')),
            ],
            options={
                'verbose_name': 'Préférence Pharmacie',
                'verbose_name_plural': 'Préférences Pharmacies',
                'unique_together': {('pharmacy', 'card')},
            },
        ),
    ]
