# Generated by Django 5.2.8 on 2025-11-26 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icon_slug', models.CharField(default='folder', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description_officielle', models.TextField(blank=True, help_text='Description par défaut')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cards/logos/')),
                ('type', models.CharField(choices=[('OFFICIAL', 'Officiel (Validé Admin)'), ('PARTNER', 'Partenaire (Géré par Labo)'), ('PRIVATE', 'Privé (Créé par Pharmacie)')], default='OFFICIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='resources.category')),
                ('owner_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('owner_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WEB', 'Site Web'), ('PDF', 'Document PDF'), ('TEL', 'Numéro de téléphone'), ('MAIL', 'Adresse Email')], default='WEB', max_length=10)),
                ('label', models.CharField(help_text='Ex: Accès Commande, Protocole...', max_length=100)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='cards/files/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.resourcecard')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes_perso', models.TextField(blank=True, help_text="Bloc notes interne pour l'équipe")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='resources.resourcecard')),
            ],
            options={
                'unique_together': {('pharmacy', 'card')},
            },
        ),
    ]
