# Generated by Django 5.2.8 on 2025-11-25 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la catégorie')),
                ('icon_slug', models.CharField(default='link', help_text="Nom de l'icône dans la librairie Frontend (ex: 'flask', 'heart')", max_length=50, verbose_name="Nom de l'icône")),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(verbose_name='URL de destination')),
                ('image', models.ImageField(blank=True, help_text='Picto ou logo spécifique pour ce lien', null=True, upload_to='links/icons/')),
                ('is_public', models.BooleanField(default=True, help_text='Si faux, invisible pour les pharmacies non-premium (exemple)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resources.category', verbose_name='Catégorie')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_links', to='partners.partner', verbose_name='Partenaire associé (Optionnel)')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
            },
        ),
    ]
