# Generated by Django 5.2.8 on 2025-11-26 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacypreference',
            name='notes_perso',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='description_officielle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
