# Generated by Django 6.0.1 on 2026-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypreference',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourcecard',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
