# Generated by Django 5.2.8 on 2025-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacypreference',
            name='notes_perso',
        ),
        migrations.AddField(
            model_name='pharmacypreference',
            name='note_courte',
            field=models.CharField(blank=True, help_text='Affichée sur la carte (max 150 caractères)', max_length=150, verbose_name='Note courte (mémo rapide)'),
        ),
        migrations.AddField(
            model_name='pharmacypreference',
            name='note_longue',
            field=models.TextField(blank=True, help_text='Notes détaillées, procédures, informations...', verbose_name='Note longue (détails)'),
        ),
    ]
