# Generated by Django 5.2.8 on 2025-11-26 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceitem_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordre'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='pharmacypreference',
            options={'verbose_name': 'Préférence Pharmacie', 'verbose_name_plural': 'Préférences Pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='resourcecard',
            options={'verbose_name': 'Carte de Ressource', 'verbose_name_plural': 'Cartes de Ressources'},
        ),
        migrations.AlterModelOptions(
            name='resourceitem',
            options={'verbose_name': 'Élément de Ressource', 'verbose_name_plural': 'Éléments de Ressources'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_slug',
            field=models.CharField(default='folder', max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='pharmacypreference',
            name='notes_perso',
            field=models.TextField(blank=True, verbose_name='Notes Privées'),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='resources.category', verbose_name="Catégorie d'affichage par défaut"),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='description_officielle',
            field=models.TextField(blank=True, verbose_name='Description officielle'),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='owner_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Titre de la carte'),
        ),
        migrations.AlterField(
            model_name='resourcecard',
            name='type',
            field=models.CharField(choices=[('OFFICIAL', 'Officiel (Validé Admin)'), ('PARTNER', 'Partenaire (Géré par Labo)'), ('PRIVATE', 'Privé (Créé par Pharmacie)')], default='OFFICIAL', max_length=20, verbose_name='Type de carte'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé du lien'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='type',
            field=models.CharField(choices=[('WEB', 'Site Web'), ('PDF', 'Document PDF'), ('TEL', 'Numéro de téléphone'), ('MAIL', 'Adresse Email')], default='WEB', max_length=10, verbose_name="Type d'élément"),
        ),
    ]
