# Generated by Django 6.0.1 on 2026-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_add_ordre_to_resourcecard_and_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecard',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icône carrée représentant la ressource (PNG/SVG recommandé, fond transparent).', null=True, upload_to='cards/icons/', verbose_name='Icône'),
        ),
    ]
