# Generated by Django 6.0.1 on 2026-03-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_pharmacypreference_notes_perso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecard',
            name='logo',
        ),
    ]
