# Generated by Django 6.0.1 on 2026-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_logo_from_resourcecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_slug',
        ),
    ]
