# Generated by Django 6.0.1 on 2026-04-05 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_icon_to_resourcecard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecard',
            name='recommendation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut recommandation'),
        ),
        migrations.AddField(
            model_name='resourcecard',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de recommandation'),
        ),
        migrations.AddField(
            model_name='resourcecard',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_cards', to=settings.AUTH_USER_MODEL, verbose_name='Recommandé par'),
        ),
        migrations.AddField(
            model_name='resourcecard',
            name='recommended_to_community',
            field=models.BooleanField(default=False, verbose_name='Recommandé à la communauté'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='recommendation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut recommandation'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de recommandation'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_items', to=settings.AUTH_USER_MODEL, verbose_name='Recommandé par'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='recommended_to_community',
            field=models.BooleanField(default=False, verbose_name='Recommandé à la communauté'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='target_official_card',
            field=models.ForeignKey(blank=True, help_text='Carte OFFICIAL sur laquelle rattacher cet item après approbation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_community_items', to='resources.resourcecard', verbose_name='Carte OFFICIAL cible'),
        ),
    ]
