# Generated by Django 5.2.8 on 2025-11-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypreference',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
