# Generated by Django 6.0.1 on 2026-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourcecard_recommendation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacypreference',
            name='note_courte',
            field=models.CharField(blank=True, default='', help_text='Affichée sur la carte (max 150 caractères)', max_length=150, verbose_name='Note courte (mémo rapide)'),
        ),
        migrations.AlterField(
            model_name='pharmacypreference',
            name='note_longue',
            field=models.TextField(blank=True, default='', help_text='Notes détaillées, procédures, informations...', verbose_name='Note longue (détails)'),
        ),
    ]
