# Generated by Django 6.0.1 on 2026-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_icon_slug_from_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie Wizard',
                'verbose_name_plural': 'Catégories Wizard',
                'ordering': ['ordre'],
            },
        ),
    ]
