# Generated by Django 5.2.8 on 2025-11-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_pharmacypreference_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypreference',
            name='assigned_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_preferences', to='resources.category', verbose_name='Catégorie assignée par le pharmacien'),
        ),
    ]
