# Generated by Django 6.0.1 on 2026-03-13 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_collaborator_contract_type_collaborator_weekly_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('cp', 'Congés payés'), ('maladie', 'Maladie'), ('rcr', 'RCR'), ('sans_solde', 'Sans solde')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='team.collaborator')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_absences', to='team.collaborator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_window', models.IntegerField(choices=[(2, '2 semaines'), (3, '3 semaines'), (4, '4 semaines')], default=2)),
                ('weekly_contract_hours', models.DecimalField(decimal_places=1, default=35.0, max_digits=4)),
                ('opening_monday', models.CharField(blank=True, default='08:30-19:30', max_length=11)),
                ('opening_tuesday', models.CharField(blank=True, default='08:30-19:30', max_length=11)),
                ('opening_wednesday', models.CharField(blank=True, default='08:30-19:30', max_length=11)),
                ('opening_thursday', models.CharField(blank=True, default='08:30-19:30', max_length=11)),
                ('opening_friday', models.CharField(blank=True, default='08:30-19:30', max_length=11)),
                ('opening_saturday', models.CharField(blank=True, default='09:00-12:00', max_length=11)),
                ('opening_sunday', models.CharField(blank=True, default='', max_length=11)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_extra_hour', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='team.collaborator')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('on_call', 'Garde')], default='open', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('pharmacy', 'date')},
            },
        ),
    ]
