# Generated by Django 6.0.1 on 2026-03-14 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('team', '0005_collaborator_contract_type_collaborator_weekly_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='posted_by_manager',
            field=models.BooleanField(default=False, help_text='True si posé directement par un manager sans demande du collaborateur'),
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'Semaine A'), ('B', 'Semaine B'), ('C', 'Semaine C'), ('D', 'Semaine D')], max_length=1)),
                ('apply_from', models.DateField(blank=True, help_text='Date à partir de laquelle ce template est appliqué', null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pharmacy', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='TemplateShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.collaborator')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='planning.weektemplate')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
