# Generated by Django 6.0.1 on 2026-03-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_absencerequest_posted_by_manager_weektemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_friday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_monday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_saturday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_sunday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_thursday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_tuesday',
        ),
        migrations.RemoveField(
            model_name='planningsettings',
            name='opening_wednesday',
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
