# Generated by Django 6.0.1 on 2026-03-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_shift_contract_hours_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsettings',
            name='weekly_contract_hours',
        ),
    ]
