# Generated by Django 6.0.1 on 2026-03-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_weekly_contract_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='type',
            field=models.CharField(choices=[('injustifiee', 'Absence injustifiée'), ('cp', 'Congés payés'), ('maladie', 'Maladie'), ('rcr', 'RCR'), ('sans_solde', 'Sans solde')], default='injustifiee', max_length=20),
        ),
    ]
