# Generated by Django 6.0.1 on 2026-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_week_template_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydaystatus',
            name='on_call_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacydaystatus',
            name='on_call_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='on_call_day_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='on_call_day_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='on_call_night_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='on_call_night_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacydaystatus',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé')], default='open', max_length=10),
        ),
    ]
