# Generated by Django 6.0.1 on 2026-03-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_injustifiee_absence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
