# Generated by Django 6.0.1 on 2026-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_garde_booleans_and_settings_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsettings',
            name='on_call_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
