# Generated by Django 6.0.1 on 2026-03-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_on_call_sunday'),
        ('team', '0006_add_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('overtime', 'Heures supplémentaires'), ('early_departure', 'Départ anticipé')], max_length=20)),
                ('actual_time', models.TimeField()),
                ('reference_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_adjustments', to='team.collaborator')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_adjustments', to='team.collaborator')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='planning.shift')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
