# Generated by Django 6.0.1 on 2026-03-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_add_shift_absence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='absence_type',
            field=models.CharField(blank=True, choices=[('injustifiee', 'Absence injustifiée'), ('justifiee', 'Absence justifiée'), ('maladie', 'Maladie'), ('cp', 'Congés payés'), ('rcr', 'RCR'), ('sans_solde', 'Sans solde')], max_length=20, null=True),
        ),
    ]
