# Generated by Django 6.0.1 on 2026-03-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_timeadjustment'),
        ('team', '0007_add_archived_at_to_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='collaborator_snapshot',
            field=models.CharField(blank=True, help_text='Nom capturé à la publication, préservé si le collab est archivé', max_length=150),
        ),
        migrations.AlterField(
            model_name='shift',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='team.collaborator'),
        ),
    ]
