# Generated by Django 6.0.1 on 2026-03-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_shift_nullable_fk_and_snapshot'),
        ('team', '0007_add_archived_at_to_collaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('regulatory', 'Réglementaire'), ('pharmacy', 'Pharmacie'), ('personal', 'Personnelle')], max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_constraints', to='team.collaborator')),
                ('constraint_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='planning.constraintset')),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
    ]
