# Generated by Django 6.0.1 on 2026-03-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_rename_justifiee_to_conge_exceptionnel'),
        ('team', '0004_alter_contracthistory_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_requests', to='team.collaborator'),
        ),
    ]
