# Generated by Django 6.0.1 on 2026-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_pg_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='working_days_count',
            field=models.IntegerField(blank=True, help_text='Nombre de jours ouvrés réellement déduits (fériés exclus pour les CP)', null=True),
        ),
    ]
