# Generated by Django 6.0.1 on 2026-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_absencerequest_working_days_count'),
        ('team', '0008_add_color_hex_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='half_day',
            field=models.BooleanField(default=False, help_text="True si l'absence ne couvre qu'une demi-journée (CP uniquement)"),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('morning', 'Matin'), ('afternoon', 'Après-midi')], help_text='Période concernée si half_day=True', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='absencerequest',
            name='working_days_count',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nombre de jours ouvrés déduits (0.5 pour demi-journée, fériés exclus pour CP)', max_digits=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(('half_day', False), ('start_date', models.F('end_date')), _connector='OR'), name='absence_half_day_requires_single_day'),
        ),
    ]
