# Generated by Django 6.0.1 on 2026-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_openinghoursversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='end_period',
            field=models.CharField(choices=[('morning', 'Matin'), ('evening', 'Soir')], default='evening', help_text="Période de fin : morning=jusqu'à 13h, evening=fin de journée (CP uniquement)", max_length=7),
        ),
        migrations.AlterField(
            model_name='absencerequest',
            name='start_period',
            field=models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi')], default='morning', help_text='Période de début : morning=dès 08h, afternoon=dès 13h (CP uniquement)', max_length=9),
        ),
        migrations.AlterField(
            model_name='absencerequest',
            name='working_days_count',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nombre de jours ouvrés CP déduits (fériés et dimanches exclus)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='absence_type',
            field=models.CharField(blank=True, choices=[('injustifiee', 'Absence injustifiée'), ('conge_exceptionnel', 'Congé exceptionnel légal'), ('maladie', 'Maladie'), ('cp', 'Congés payés'), ('rcr', 'RCR'), ('sans_solde', 'Sans solde'), ('formation', 'Formation')], max_length=20, null=True),
        ),
    ]
